// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = 'https://qnorggoycwbbxdlvbcvq.supabase.co';
const DEFAULT_SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFub3JnZ295Y3diYnhkbHZiY3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk0Njc2MzIsImV4cCI6MjEwNTA0MzYzMn0.p5u-b8QH1PIuiS1QWs716K-nporm3gnM4P1QDe-eQZg';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL?.trim() || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() || DEFAULT_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Recovery emails come back with a one-time code. The session tokens stay in
    // storage and are not written into the address bar.
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});
